/**
 * Serves rich OG/Twitter meta for /vote/:slug links to social crawlers.
 * Real browsers never hit this — vercel.json only routes known bot user-agents here.
 * The og:image is generated by /api/og-image and carries the category sponsor's name.
 */

const SUPABASE_URL = process.env.VITE_SUPABASE_URL as string;
const ANON_KEY = (process.env.VITE_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY) as string;

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

async function sb(path: string): Promise<any[]> {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
    headers: { apikey: ANON_KEY, Authorization: `Bearer ${ANON_KEY}` },
  });
  if (!res.ok) return [];
  return res.json();
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export default async function handler(req: any, res: any) {
  const slug = String(req.query.slug || "");
  let nomination: any = null;

  try {
    if (UUID_RE.test(slug)) {
      const rows = await sb(`nominations?id=eq.${slug}&select=id,podcast_name,podcaster_name,category_id&limit=1`);
      nomination = rows[0] || null;
    } else if (slug) {
      // Legacy custom voting links resolve through the podcaster's profile
      const profiles = await sb(`profiles?custom_voting_link=eq.${encodeURIComponent(slug)}&select=id&limit=1`);
      if (profiles[0]) {
        const rows = await sb(`nominations?user_id=eq.${profiles[0].id}&select=id,podcast_name,podcaster_name,category_id&limit=1`);
        nomination = rows[0] || null;
      }
    }
  } catch {
    nomination = null;
  }

  let categoryName = "";
  let sponsorName = "";
  if (nomination?.category_id) {
    const [cats, sponsors] = await Promise.all([
      sb(`award_categories?id=eq.${nomination.category_id}&select=name&limit=1`),
      sb(`sponsors?category_id=eq.${nomination.category_id}&is_active=eq.true&select=name&limit=1`),
    ]);
    categoryName = cats[0]?.name || "";
    sponsorName = sponsors[0]?.name || "";
  }

  const show = nomination?.podcast_name || "a veteran podcast";
  const title = nomination
    ? `Vote for ${show} — 2026 Veteran Podcast Awards`
    : "2026 Veteran Podcast Awards";
  const descParts = [
    nomination ? `${show} is nominated${categoryName ? ` for ${categoryName}` : ""}.` : "Celebrating the voices of veteran podcasters.",
    "Voting is open — cast your vote in 30 seconds.",
  ];
  if (sponsorName) descParts.push(`${categoryName || "Category"} presented by ${sponsorName}.`);
  const description = descParts.join(" ");

  const ogParams = new URLSearchParams();
  if (nomination?.podcast_name) ogParams.set("show", nomination.podcast_name);
  if (categoryName) ogParams.set("category", categoryName);
  if (sponsorName) ogParams.set("sponsor", sponsorName);
  const ogImage = `https://veteranpodcastawards.com/api/og-image?${ogParams.toString()}`;
  const pageUrl = `https://veteranpodcastawards.com/vote/${slug}`;

  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.setHeader("Cache-Control", "public, s-maxage=600, stale-while-revalidate=3600");
  res.status(200).send(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Veteran Podcast Awards" />
  <meta property="og:title" content="${esc(title)}" />
  <meta property="og:description" content="${esc(description)}" />
  <meta property="og:url" content="${esc(pageUrl)}" />
  <meta property="og:image" content="${esc(ogImage)}" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${esc(title)}" />
  <meta name="twitter:description" content="${esc(description)}" />
  <meta name="twitter:image" content="${esc(ogImage)}" />
  <meta http-equiv="refresh" content="0;url=${esc(pageUrl)}" />
</head>
<body></body>
</html>`);
}
